# Path-to-label mapping for .github/workflows/labeler.yml.
backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**"

ios:
  - changed-files:
      - any-glob-to-any-file: "RaceControlApp/**"

android:
  - changed-files:
      - any-glob-to-any-file: "RaceControlAndroid/**"

web:
  - changed-files:
      - any-glob-to-any-file: "RaceControlWeb/**"

site:
  - changed-files:
      - any-glob-to-any-file: "RaceControlSite/**"

docs:
  - changed-files:
      - any-glob-to-any-file: "RaceControlDocs/**"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

documentation:
  - changed-files:
      - any-glob-to-any-file: ["**/*.md", "RaceControlDocs/**"]
